# Generated by Django 3.2.7 on 2022-11-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_place_ev',
            name='price_type',
            field=models.CharField(choices=[('per_day', 'PER DAY'), ('per_event', 'PER EVENT'), ('per_hour', 'PER HOUR')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='add_service_ev',
            name='service_price_type',
            field=models.CharField(choices=[('per_day', 'Per Day'), ('per_person', 'Per Person'), ('per_event', 'Per Event')], default='per_day', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('0', 'HOME PAGE'), ('1', 'EVENT LISTING PAGE'), ('2', 'EVENT VIEW PAGE')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventpersonaldetails',
            name='price_type',
            field=models.CharField(choices=[('per_day', 'PER DAY'), ('per_event', 'PER EVENT'), ('per_hour', 'PER HOUR')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_type',
            field=models.CharField(choices=[('personal_skills', 'Personal Skills Bussiness'), ('group_skills', 'Group Skills Bussiness'), ('places', 'Have You Place')], default='places', max_length=50),
        ),
        migrations.AlterField(
            model_name='pc_artist',
            name='price_type',
            field=models.CharField(choices=[('2', 'PER DAY'), ('1', 'PER HOUR')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='pc_equipments',
            name='equ_price_type',
            field=models.CharField(choices=[('2', 'PER DAY'), ('1', 'PER HOUR')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='ps_equipments',
            name='equ_price_type',
            field=models.CharField(choices=[('2', 'PER DAY'), ('1', 'PER HOUR')], default=0, max_length=255),
        ),
    ]
