# Generated by Django 3.2.7 on 2022-10-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0002_auto_20220906_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpersonaldetails',
            name='price_type',
            field=models.CharField(choices=[('per_event', 'PER EVENT'), ('per_day', 'PER DAY'), ('per_hour', 'PER HOUR')], default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='eventpersonaldetails',
            name='skill_banner',
            field=models.FileField(blank=True, null=True, upload_to='personal_details/banner/'),
        ),
        migrations.AlterField(
            model_name='add_service_ev',
            name='service_price_type',
            field=models.CharField(choices=[('per_person', 'Per Person'), ('per_day', 'Per Day'), ('per_event', 'Per Event')], default='per_day', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('1', 'EVENT LISTING PAGE'), ('2', 'EVENT VIEW PAGE'), ('0', 'HOME PAGE')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='event_type',
            field=models.CharField(choices=[('group_skills', 'Group Skills Bussiness'), ('personal_skills', 'Personal Skills Bussiness'), ('places', 'Have You Place')], default='places', max_length=50),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_type',
            field=models.CharField(choices=[('advance_and_discount_confirmation', 'Advance And Discount Confirmation'), ('discount_on_equipment_or_item', 'Discount On Equipment Or Item'), ('discount_on_total_bill', 'Discount On Total Bill')], max_length=50),
        ),
        migrations.AlterField(
            model_name='place_events',
            name='IncludingFacilities',
            field=models.CharField(choices=[('romantic_lunch_dinner', 'Romantic Lunch/Dinner'), ('romantic_candlelight_dinner', 'Romantic Candlelight Dinner'), ('romantic_stay', 'Romantic Stay')], default='romantic_stay', max_length=100),
        ),
    ]
