# Generated by Django 3.2.7 on 2022-10-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0004_auto_20221007_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_place_ev',
            name='price_type',
            field=models.CharField(choices=[('per_day', 'PER DAY'), ('per_hour', 'PER HOUR'), ('per_event', 'PER EVENT')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='add_service_ev',
            name='service_price_type',
            field=models.CharField(choices=[('per_day', 'Per Day'), ('per_person', 'Per Person'), ('per_event', 'Per Event')], default='per_day', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('0', 'HOME PAGE'), ('2', 'EVENT VIEW PAGE'), ('1', 'EVENT LISTING PAGE')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='event_type',
            field=models.CharField(choices=[('places', 'Have You Place'), ('personal_skills', 'Personal Skills Bussiness'), ('group_skills', 'Group Skills Bussiness')], default='places', max_length=50),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_type',
            field=models.CharField(choices=[('discount_on_equipment_or_item', 'Discount On Equipment Or Item'), ('advance_and_discount_confirmation', 'Advance And Discount Confirmation'), ('discount_on_total_bill', 'Discount On Total Bill')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eventcompanyimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/events/company'),
        ),
        migrations.AlterField(
            model_name='eventcompanyvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='image/events/company/video'),
        ),
        migrations.AlterField(
            model_name='eventpersonaldetails',
            name='price_type',
            field=models.CharField(choices=[('per_day', 'PER DAY'), ('per_hour', 'PER HOUR'), ('per_event', 'PER EVENT')], default=0, max_length=255),
        ),
    ]
