# Generated by Django 3.2.7 on 2022-10-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0004_auto_20221017_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgdiscounts',
            old_name='orgdiscount',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='orgdiscounts',
            name='orgdescription',
        ),
        migrations.RemoveField(
            model_name='orgdiscounts',
            name='orgdiscount_id',
        ),
        migrations.RemoveField(
            model_name='orgdiscounts',
            name='orgdiscountsId',
        ),
        migrations.RemoveField(
            model_name='orgdiscounts',
            name='orgequipment',
        ),
        migrations.RemoveField(
            model_name='orgdiscounts',
            name='orguser',
        ),
        migrations.AddField(
            model_name='orgdiscounts',
            name='discount_type',
            field=models.CharField(choices=[('discount_on_equipment_or_item', 'Discount On Equipment Or Item'), ('discount_on_total_bill', 'Discount On Total Bill'), ('advance_and_discount_confirmation', 'Advance And Discount Confirmation')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgdiscounts',
            name='event_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userApi.eventtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgdiscounts',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgdiscounts',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userApi.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_place_ev',
            name='price_type',
            field=models.CharField(choices=[('per_hour', 'PER HOUR'), ('per_day', 'PER DAY'), ('per_event', 'PER EVENT')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('1', 'EVENT LISTING PAGE'), ('2', 'EVENT VIEW PAGE'), ('0', 'HOME PAGE')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_type',
            field=models.CharField(choices=[('discount_on_equipment_or_item', 'Discount On Equipment Or Item'), ('discount_on_total_bill', 'Discount On Total Bill'), ('advance_and_discount_confirmation', 'Advance And Discount Confirmation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventpersonaldetails',
            name='price_type',
            field=models.CharField(choices=[('per_hour', 'PER HOUR'), ('per_day', 'PER DAY'), ('per_event', 'PER EVENT')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_type',
            field=models.CharField(choices=[('personal_skills', 'Personal Skills Bussiness'), ('places', 'Have You Place'), ('group_skills', 'Group Skills Bussiness')], default='places', max_length=50),
        ),
        migrations.AlterField(
            model_name='orgdiscounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pc_artist',
            name='price_type',
            field=models.CharField(choices=[('1', 'PER HOUR'), ('2', 'PER DAY')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='pc_equipments',
            name='equ_price_type',
            field=models.CharField(choices=[('1', 'PER HOUR'), ('2', 'PER DAY')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='place_events',
            name='IncludingFacilities',
            field=models.CharField(choices=[('romantic_candlelight_dinner', 'Romantic Candlelight Dinner'), ('romantic_lunch_dinner', 'Romantic Lunch/Dinner'), ('romantic_stay', 'Romantic Stay')], default='romantic_stay', max_length=100),
        ),
        migrations.AlterField(
            model_name='ps_equipments',
            name='equ_price_type',
            field=models.CharField(choices=[('1', 'PER HOUR'), ('2', 'PER DAY')], default=0, max_length=255),
        ),
        migrations.CreateModel(
            name='OrgEquipmentId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_id', to='userApi.add_service_ev')),
                ('orgdiscount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgdiscount_id', to='userApi.orgdiscounts')),
            ],
        ),
    ]
