# Generated by Django 3.2.7 on 2022-11-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0004_auto_20221117_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='serivceId',
        ),
        migrations.AlterField(
            model_name='add_service_ev',
            name='service_price_type',
            field=models.CharField(choices=[('per_day', 'Per Day'), ('per_event', 'Per Event'), ('per_person', 'Per Person')], default='per_day', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('1', 'EVENT LISTING PAGE'), ('0', 'HOME PAGE'), ('2', 'EVENT VIEW PAGE')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_type',
            field=models.CharField(choices=[('advance_and_discount_confirmation', 'Advance And Discount Confirmation'), ('discount_on_equipment_or_item', 'Discount On Equipment Or Item'), ('discount_on_total_bill', 'Discount On Total Bill')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orgdiscounts',
            name='discount_type',
            field=models.CharField(choices=[('advance_and_discount_confirmation', 'Advance And Discount Confirmation'), ('discount_on_equipment_or_item', 'Discount On Equipment Or Item'), ('discount_on_total_bill', 'Discount On Total Bill')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pc_artist',
            name='price_type',
            field=models.CharField(choices=[('2', 'PER DAY'), ('1', 'PER HOUR')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='pc_equipments',
            name='equ_price_type',
            field=models.CharField(choices=[('2', 'PER DAY'), ('1', 'PER HOUR')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='ps_equipments',
            name='equ_price_type',
            field=models.CharField(choices=[('2', 'PER DAY'), ('1', 'PER HOUR')], default=0, max_length=255),
        ),
        migrations.CreateModel(
            name='EventWithServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('timestampe', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.eventtype')),
                ('selected_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_service', to='userApi.add_service_ev')),
            ],
        ),
        migrations.CreateModel(
            name='EventWithDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('timestampe', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.eventtype')),
                ('selected_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_discount', to='userApi.orgdiscounts')),
            ],
        ),
    ]
