# Generated by Django 3.2.7 on 2022-11-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0006_auto_20221117_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_place_ev',
            name='price_type',
            field=models.CharField(choices=[('per_hour', 'PER HOUR'), ('per_event', 'PER EVENT'), ('per_day', 'PER DAY')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('1', 'EVENT LISTING PAGE'), ('2', 'EVENT VIEW PAGE'), ('0', 'HOME PAGE')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='discountId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_id', to='userApi.orgdiscounts'),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='serivceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_id', to='userApi.add_service_ev'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_type',
            field=models.CharField(choices=[('advance_and_discount_confirmation', 'Advance And Discount Confirmation'), ('discount_on_total_bill', 'Discount On Total Bill'), ('discount_on_equipment_or_item', 'Discount On Equipment Or Item')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eventpersonaldetails',
            name='price_type',
            field=models.CharField(choices=[('per_hour', 'PER HOUR'), ('per_event', 'PER EVENT'), ('per_day', 'PER DAY')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_type',
            field=models.CharField(choices=[('group_skills', 'Group Skills Bussiness'), ('personal_skills', 'Personal Skills Bussiness'), ('places', 'Have You Place')], default='places', max_length=50),
        ),
        migrations.AlterField(
            model_name='orgdiscounts',
            name='discount_type',
            field=models.CharField(choices=[('advance_and_discount_confirmation', 'Advance And Discount Confirmation'), ('discount_on_total_bill', 'Discount On Total Bill'), ('discount_on_equipment_or_item', 'Discount On Equipment Or Item')], max_length=50),
        ),
        migrations.AlterField(
            model_name='place_events',
            name='IncludingFacilities',
            field=models.CharField(choices=[('romantic_stay', 'Romantic Stay'), ('romantic_candlelight_dinner', 'Romantic Candlelight Dinner'), ('romantic_lunch_dinner', 'Romantic Lunch/Dinner')], default='romantic_stay', max_length=100),
        ),
    ]
