# Generated by Django 3.2.7 on 2022-10-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0006_auto_20221007_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='add_place_ev',
            name='price_type',
            field=models.CharField(choices=[('per_event', 'PER EVENT'), ('per_hour', 'PER HOUR'), ('per_day', 'PER DAY')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='add_service_ev',
            name='service_price_type',
            field=models.CharField(choices=[('per_day', 'Per Day'), ('per_person', 'Per Person'), ('per_event', 'Per Event')], default='per_day', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('0', 'HOME PAGE'), ('1', 'EVENT LISTING PAGE'), ('2', 'EVENT VIEW PAGE')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_type',
            field=models.CharField(choices=[('discount_on_total_bill', 'Discount On Total Bill'), ('advance_and_discount_confirmation', 'Advance And Discount Confirmation'), ('discount_on_equipment_or_item', 'Discount On Equipment Or Item')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eventpersonaldetails',
            name='price_type',
            field=models.CharField(choices=[('per_event', 'PER EVENT'), ('per_hour', 'PER HOUR'), ('per_day', 'PER DAY')], default=0, max_length=255),
        ),
    ]
