# Generated by Django 3.2.7 on 2022-10-14 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0007_auto_20221014_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_place_ev',
            name='price_type',
            field=models.CharField(choices=[('per_day', 'PER DAY'), ('per_hour', 'PER HOUR'), ('per_event', 'PER EVENT')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='add_service_ev',
            name='service_price_type',
            field=models.CharField(choices=[('per_person', 'Per Person'), ('per_day', 'Per Day'), ('per_event', 'Per Event')], default='per_day', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('0', 'HOME PAGE'), ('2', 'EVENT VIEW PAGE'), ('1', 'EVENT LISTING PAGE')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='event_type',
            field=models.CharField(choices=[('places', 'Have You Place'), ('group_skills', 'Group Skills Bussiness'), ('personal_skills', 'Personal Skills Bussiness')], default='places', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventpersonaldetails',
            name='price_type',
            field=models.CharField(choices=[('per_day', 'PER DAY'), ('per_hour', 'PER HOUR'), ('per_event', 'PER EVENT')], default=0, max_length=255),
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('places', 'Have You Place'), ('group_skills', 'Group Skills Bussiness'), ('personal_skills', 'Personal Skills Bussiness')], default='places', max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('timestampe', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='userApi.eventcategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
