# Generated by Django 3.2.7 on 2022-11-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0007_auto_20221117_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_place_ev',
            name='price_type',
            field=models.CharField(choices=[('per_hour', 'PER HOUR'), ('per_day', 'PER DAY'), ('per_event', 'PER EVENT')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='add_service_ev',
            name='service_price_type',
            field=models.CharField(choices=[('per_event', 'Per Event'), ('per_day', 'Per Day'), ('per_person', 'Per Person')], default='per_day', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('0', 'HOME PAGE'), ('2', 'EVENT VIEW PAGE'), ('1', 'EVENT LISTING PAGE')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='discountId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_id', to='userApi.orgdiscounts'),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='serivceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_id', to='userApi.add_service_ev'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_type',
            field=models.CharField(choices=[('discount_on_total_bill', 'Discount On Total Bill'), ('advance_and_discount_confirmation', 'Advance And Discount Confirmation'), ('discount_on_equipment_or_item', 'Discount On Equipment Or Item')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eventpersonaldetails',
            name='price_type',
            field=models.CharField(choices=[('per_hour', 'PER HOUR'), ('per_day', 'PER DAY'), ('per_event', 'PER EVENT')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_type',
            field=models.CharField(choices=[('places', 'Have You Place'), ('group_skills', 'Group Skills Bussiness'), ('personal_skills', 'Personal Skills Bussiness')], default='places', max_length=50),
        ),
        migrations.AlterField(
            model_name='orgdiscounts',
            name='discount_type',
            field=models.CharField(choices=[('discount_on_total_bill', 'Discount On Total Bill'), ('advance_and_discount_confirmation', 'Advance And Discount Confirmation'), ('discount_on_equipment_or_item', 'Discount On Equipment Or Item')], max_length=50),
        ),
        migrations.AlterField(
            model_name='place_events',
            name='IncludingFacilities',
            field=models.CharField(choices=[('romantic_candlelight_dinner', 'Romantic Candlelight Dinner'), ('romantic_stay', 'Romantic Stay'), ('romantic_lunch_dinner', 'Romantic Lunch/Dinner')], default='romantic_stay', max_length=100),
        ),
    ]
