# Generated by Django 3.2.7 on 2022-09-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0008_auto_20220824_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='display_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='add_place_ev',
            name='price_type',
            field=models.CharField(choices=[('per_event', 'PER EVENT'), ('per_day', 'PER DAY'), ('per_hour', 'PER HOUR')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='add_service_ev',
            name='service_price_type',
            field=models.CharField(choices=[('per_person', 'Per Person'), ('per_event', 'Per Event'), ('per_day', 'Per Day')], default='per_day', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('2', 'EVENT VIEW PAGE'), ('1', 'EVENT LISTING PAGE'), ('0', 'HOME PAGE')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='event_type',
            field=models.CharField(choices=[('group_skills', 'Group Skills Bussiness'), ('places', 'Have You Place'), ('personal_skills', 'Personal Skills Bussiness')], default='places', max_length=50),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_type',
            field=models.CharField(choices=[('discount_on_total_bill', 'Discount On Total Bill'), ('discount_on_equipment_or_item', 'Discount On Equipment Or Item'), ('advance_and_discount_confirmation', 'Advance And Discount Confirmation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pc_artist',
            name='price_type',
            field=models.CharField(choices=[('2', 'PER DAY'), ('1', 'PER HOUR')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='pc_equipments',
            name='equ_price_type',
            field=models.CharField(choices=[('2', 'PER DAY'), ('1', 'PER HOUR')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='ps_equipments',
            name='equ_price_type',
            field=models.CharField(choices=[('2', 'PER DAY'), ('1', 'PER HOUR')], default=0, max_length=255),
        ),
    ]
