# Generated by Django 3.2.7 on 2022-10-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0012_auto_20221014_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_service_ev',
            name='service_price_type',
            field=models.CharField(choices=[('per_day', 'Per Day'), ('per_person', 'Per Person'), ('per_event', 'Per Event')], default='per_day', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('2', 'EVENT VIEW PAGE'), ('1', 'EVENT LISTING PAGE'), ('0', 'HOME PAGE')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='event_type',
            field=models.CharField(choices=[('personal_skills', 'Personal Skills Bussiness'), ('group_skills', 'Group Skills Bussiness'), ('places', 'Have You Place')], default='places', max_length=50),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_type',
            field=models.CharField(choices=[('advance_and_discount_confirmation', 'Advance And Discount Confirmation'), ('discount_on_total_bill', 'Discount On Total Bill'), ('discount_on_equipment_or_item', 'Discount On Equipment Or Item')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_type',
            field=models.CharField(choices=[('personal_skills', 'Personal Skills Bussiness'), ('group_skills', 'Group Skills Bussiness'), ('places', 'Have You Place')], default='places', max_length=50),
        ),
    ]
